name: tf apply
description: Apply Terraform configuration


inputs:
  tf_state_bucket:
    type: string
    description: The bucket that contains the Terraform state.
    required: true
  tf_state_key:
    type: string
    description: The key that contains the Terraform state.
    required: true
  aws_region:
    type: string
    description: The AWS region.
    required: true
  static_assets_bucket:
    type: string
    description: The bucket that contains the static assets.
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Create backend.tf
      shell: bash
      run: |
        cat <<EOF > ./infra/terraform/backend.tf
        terraform {
          backend "s3" {}
        }
        EOF

    - name: TF Init
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.tf_state_bucket }}" \
          -backend-config="key=${{ inputs.tf_state_key }}" \
          -backend-config="region=${{ inputs.aws_region }}"
      working-directory: ./infra/terraform

    - name: TF Apply
      shell: bash
      id: apply
      run: terraform apply -no-color --auto-approve --var region=${{ inputs.aws_region }}
      working-directory: ./infra/terraform
      continue-on-error: true

    - name: APP URL
      shell: bash
      run: |
        terraform output | grep function_url | cut -d " " -f 3
      working-directory: ./infra/terraform
