name: manual-pull-infra-changes

on:
  workflow_dispatch: {}

env:
  AWS_REGION: "us-west-2"

jobs:
  pull-appstack:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IaC
        uses: appcd-dev/download-action@v0.5
        env:
          APPCD_URL: https://cloud.stackgen.com
          APPCD_TOKEN: ${{ secrets.APPCD_TOKEN }}
        with:
          appstack_uuid: ${{ vars.APPSTACK_UUID }}
          output: ./infra
          latest: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::222634395437:role/sep-24-meetup-oidc-github
          aws-region: ${{ env.AWS_REGION }}

      - name: Update IaC in PR
        uses: ./.github/workflows/infra-create-pr
        with:
          tf_state_bucket: ${{ vars.TF_STATE_BUCKET }}
          tf_state_key: ${{ github.repository }}/terraform.tfstate
          aws_region: ${{ env.AWS_REGION }}
